### ISSUE TITLE
missing feature

### ISSUE THREAD

**Issue by MrBreakNFix** [FlorianMichael/UI-Utils-Reborn#4]
its missing the funny sugar thing :D 

i can make a pr for it

**Comment by FlorianMichael** [comment]
What's that?

**Comment by FlorianMichael** [comment]
No

**Comment by DOLAD548** [comment]
Can you please help me i am trying to use it to auctionhouse dupe but i cant seem to put my item in the auctionhouse after saving and closing without the packets gui
